-- only Forum / Community Board tables
-- TO apply on the existing Mikurando database.

CREATE TABLE IF NOT EXISTS "Forum_Thread" (
  thread_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  restaurant_id integer NOT NULL,
  user_id integer NOT NULL,
  title text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  is_closed boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS "Forum_Post" (
  post_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  thread_id integer NOT NULL,
  user_id integer NOT NULL,
  content text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  is_approved boolean NOT NULL DEFAULT true
);

DO $$ BEGIN
  ALTER TABLE "Forum_Thread"
    ADD CONSTRAINT forum_thread_restaurant_fk
    FOREIGN KEY (restaurant_id) REFERENCES "Restaurant" (restaurant_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "Forum_Thread"
    ADD CONSTRAINT forum_thread_user_fk
    FOREIGN KEY (user_id) REFERENCES "User" (user_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "Forum_Post"
    ADD CONSTRAINT forum_post_thread_fk
    FOREIGN KEY (thread_id) REFERENCES "Forum_Thread" (thread_id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "Forum_Post"
    ADD CONSTRAINT forum_post_user_fk
    FOREIGN KEY (user_id) REFERENCES "User" (user_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
